export const TEST_DISPATCH = 'TEST_DISPATCH';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const ADD_CLIENT = 'ADD_CLIENT';
export const ADD_USER = 'ADD_USER';



export const ORDER_ITEM_COUNT = 'ORDER_ITEM_COUNT';
export const INCRESS_ORDER_ITEM = 'INCRESS_ORDER_ITEM';
export const ADD_CHANGE_ORDER_ITEM = 'ADD_CHANGE_ORDER_ITEM';
export const ADD_ORDER_ITEM = 'ADD_ORDER_ITEM';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const DROP_ORDER_ITEM = 'DROP_ORDER_ITEM';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
